name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.66.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png


